contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #dryad channel"
    url: https://nfcore.slack.com/channels/dryad
    about: Discussion about the nf-core/dryad pipeline
